export default [
  {
    id: 12471,
    bgImg: "imgs/course-01.jpg",
    instructorImg: "imgs/team-01.png",
    title: "Mastering Web Design",
    description: "Master The Art Of Web Designing And Mocking, Prototyping And Creating Web Design Architecture",
    subscribers: 950,
    price: 165,
  },
  {
    id: 42136,
    bgImg: "imgs/course-02.jpg",
    instructorImg: "imgs/team-02.png",
    title: "Data Structure And Algorithms",
    description: "Master The Art Of Data Strcuture And Famous Algorithms Like Sorting, Dividing And Conquering",
    subscribers: 1150,
    price: 210,
  },
  {
    id: 28941,
    bgImg: "imgs/course-03.jpg",
    instructorImg: "imgs/team-03.png",
    title: "Responsive Web Design",
    description: "Mastering Responsive Web Design And Media Queries And Know Everything About Breakpoints",
    subscribers: 650,
    price: 90,
  },
  {
    id: 49321,
    bgImg: "imgs/course-04.jpg",
    instructorImg: "imgs/team-04.png",
    title: "Mastering Python",
    description: "Mastering Python To Prepare For Data Science And AI And Automating Things in Your Life",
    subscribers: 950,
    price: 250,
  },
  {
    id: 58123,
    bgImg: "imgs/course-05.jpg",
    instructorImg: "imgs/team-05.png",
    title: "PHP Examples",
    description: "PHP Tutorials And Examples And Practice On Web Application And Connecting With Databases",
    subscribers: 850,
    price: 150,
  },
  {
    id: 25424,
    bgImg: "imgs/course-02.jpg",
    instructorImg: "imgs/team-05.png",
    title: "Data Structure And Algorithms",
    description: "Master The Art Of Data Strcuture And Famous Algorithms Like Sorting, Dividing And Conquering",
    subscribers: 1150,
    price: 210,
  },
  {
    id: 42901,
    bgImg: "imgs/course-01.jpg",
    instructorImg: "imgs/team-01.png",
    title: "Responsive Web Design",
    description: "Mastering Responsive Web Design And Media Queries And Know Everything About Breakpoints",
    subscribers: 650,
    price: 90,
  },
  {
    id: 83921,
    bgImg: "imgs/course-04.jpg",
    instructorImg: "imgs/team-03.png",
    title: "Mastering Web Design",
    description: "Master The Art Of Web Designing And Mocking, Prototyping And Creating Web Design Architecture",
    subscribers: 850,
    price: 145,
  },
  {
    id: 90293,
    bgImg: "imgs/course-03.jpg",
    instructorImg: "imgs/team-02.png",
    title: "PHP Examples",
    description: "PHP Tutorials And Examples And Practice On Web Application And Connecting With Databases",
    subscribers: 850,
    price: 150,
  },
  {
    id: 51265,
    bgImg: "imgs/course-01.jpg",
    instructorImg: "imgs/team-05.png",
    title: "Mastering Python",
    description: "Mastering Python To Prepare For Data Science And AI And Automating Things in Your Life",
    subscribers: 950,
    price: 250,
  },
]